Models/Rentail.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace RentCarHub1.Models
{
    public partial class Rentail
    {
        public int Id { get; set; }
        public string Carid { get; set; }
        public int? Custid { get; set; }
        public int? Fee { get; set; }
        public DateTime? Sdate { get; set; }
        public DateTime? Edate { get; set; }
    }
}

Models/RentailViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace RentCarHub1.Models
{
    public class RentailViewModel
    {
        public int Id { get; set; }
        public string Carid { get; set; }
        public int? Custid { get; set; }
        public int? Fee { get; set; }
        public DateTime? Sdate { get; set; }
        public DateTime? Edate { get; set; }
        public string Available { get; set; }
    }
}

Controllers/RentailController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RentCarHub1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RentCarHub1.Controllers
{
    public class RentailController : Controller
    {
        RentCarContext db = new RentCarContext();
        // GET: Rentail
        public ActionResult Index()
        {
            var result = (from r in db.Rentails
                          join c in db.Carregs on r.Carid equals c.Carno
                          select new RentailViewModel
                          {
                              Id = r.Id,
                              Carid = r.Carid,
                              Custid = r.Custid,
                              Fee = r.Fee,
                              Sdate = r.Sdate,
                              Edate = r.Edate,
                              Available = c.Available
                          }).ToList();
            return View(result);
        }

        [HttpGet]
        public ActionResult Getcar()
        {
            var car = db.Carregs.ToList();
            return Json(car);
        }

        [HttpPost]
        public ActionResult Getid(int id)
        {
            var customer = (from s in db.Customers where s.Id == id select s.Cutname).ToList();
            return Json(customer);
        }

        [HttpPost]
        public ActionResult Getavail(string carno)
        {
            var caravail = (from s in db.Carregs where s.Carno == carno select s.Available).FirstOrDefault();
            return Json(caravail);
        }

        [HttpPost]
        public ActionResult Save(Rentail rent)
        {
            if (ModelState.IsValid)
            {
                db.Rentails.Add(rent);
                var car = db.Carregs.SingleOrDefault(e => e.Carno == rent.Carid);


                car.Available = "no";
                db.Entry(car).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(rent);
        }
    }
}

Views/Rentail/Index.cshtml
@model IEnumerable<RentCarHub1.Models.RentailViewModel>

<div class="row">

    <div class="col-sm-4">

        @using (Html.BeginForm("Save", "Rentail", FormMethod.Post, new { id = "popupForm" }))
        {
            <div>
                <h1>Car Rentail</h1>
            </div>

            <div class="form-group">
                <label class="form-label">Car No</label>
                <select class="form-control" id="carid" name="carid" placeholder="CarNo" required>
                    <option>Please Select</option>
                </select>
            </div>

            <div class="form-group">
                <label class="form-label">Customer id</label>
                <input type="text" id="custid" name="custid" class="form-control" placeholder="CustId" required />
            </div>

            <div class="form-group">
                <label class="form-label">Customer Name</label>
                <input type="text" id="custname" name="custName" class="form-control" placeholder="CustName" required />
            </div>

            <div class="form-group">
                <label class="form-label">Rentail Fee</label>
                <input type="text" id="fee" name="fee" class="form-control" placeholder="fee" required />
            </div>

            <div class="form-group">
                <label class="form-label">Start Date</label>
                <input type="date" id="sdate" name="sdate" class="form-control" placeholder="sdate" required />
            </div>

            <div class="form-group">
                <label class="form-label">End Date</label>
                <input type="date" id="edate" name="edate" class="form-control" placeholder="edate" required />
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        }
    </div>

    <div class="col-sm-8">
        <table class="table">
            <tr>
                <th>CarNo</th>
                <th>CustomerId</th>
                <th>Fee</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Available</th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Carid</td>
                    <td>@item.Custid</td>
                    <td>@item.Fee</td>
                    <td>@item.Sdate</td>
                    <td>@item.Edate</td>
                    <td>@item.Available</td>
                </tr>
            }
        </table>
    </div>

</div>

@section scripts
{

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery/dist/jquery.js"></script>

    <script>
        getCar();
        load();
        function load() {
            $("#custid").attr("disabled", "disabled");
            $("#custname").attr("disabled", "disabled");
            $("#fee").attr("disabled", "disabled");
            $("#sdate").attr("disabled", "disabled");
            $("#edate").attr("disabled", "disabled");
        }

        function getCar() {
            $.ajax({
                type: 'GET',
                url: 'Rentail/Getcar',
                dataType: 'JSON',
                success: function (data) {
                    console.log(data);
                    for (var i = 0; i < data.length; i++) {
                        $("#carid").append($("<option/>", {
                            text: data[i].carno
                        }))
                    }
                }
            });
        }

        $("#carid").change(function () {
            available();
        });

        function available() {
            $.ajax({
                type: 'POST',
                url: 'Rentail/Getavail?carno=' + $("#carid").val(),
                dataType: 'JSON',
                success: function (data) {
                    console.log(data);
                    var avl = data;

                    if (avl === "yes") {
                        $("#custid").removeAttr('disabled');
                        $("#custname").removeAttr('disabled');
                        $("#fee").removeAttr('disabled');
                        $("#sdate").removeAttr('disabled');
                        $("#edate").removeAttr('disabled');
                    }
                    else {
                        $("#custid").attr("disabled", "disabled");
                        $("#custname").attr("disabled", "disabled");
                        $("#fee").attr("disabled", "disabled");
                        $("#sdate").attr("disabled", "disabled");
                        $("#edate").attr("disabled", "disabled");
                    }
                }
            })
        }

        getCustomer();
        function getCustomer() {
            $("#custid").keyup(function (e) {
                $.ajax({
                    type: 'POST',
                    url: 'Rentail/Getid?id=' + $("#custid").val(),
                    dataType: 'JSON',
                    success: function (data) {
                        $("#custname").val(data)
                    }
                })
            });
        }

    </script>

}