Models/Returncar.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace RentCarHub1.Models
{
    public partial class Returncar
    {
        public int Id { get; set; }
        public string Carno { get; set; }
        public int? Custid { get; set; }
        public DateTime? Date { get; set; }
        public int? Elsp { get; set; }
        public int? Fine { get; set; }
    }
}

Controllers/ReturnCarController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RentCarHub1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RentCarHub1.Controllers
{
    public class ReturnCarController : Controller
    {
        RentCarContext db = new RentCarContext();
        // GET: ReturnCar
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Save(Returncar recar)
        {
            if (ModelState.IsValid)
            {
                db.Returncars.Add(recar);
                var car = db.Carregs.SingleOrDefault(e => e.Carno == recar.Carno);


                car.Available = "yes";
                db.Entry(car).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(recar);
        }



        [HttpPost]
        public ActionResult Getid(string carno)
        {
            var cars = (from s in db.Rentails
                        where s.Carid == carno
                        select new
                        {
                            startdate = s.Sdate,
                            enddate = s.Edate,
                            custid = s.Custid,
                            carno = s.Carid,
                            fee = s.Fee,
                        }).ToArray();
            return Json(cars);
        }
    }
}

Views/ReturnCar/Index.cshtml
<div class="row">
    <div class="col-sm-4">

        @using (Html.BeginForm("Save", "ReturnCar", FormMethod.Post, new { id = "popupForm" }))
        {
            <div>
                <h1>Car Rentail</h1>
            </div>

            <div class="form-group">
                <label class="form-label">Car No</label>
                <input type="text" id="carno" name="carno" class="form-control" placeholder="carid" required />

            </div>

            <div class="form-group">
                <label class="form-label">Customer id</label>
                <input type="text" id="custid" name="custid" class="form-control" placeholder="CustId" required />
            </div>

            <div class="form-group">
                <label class="form-label">Date</label>
                <input type="text" id="date" name="date" class="form-control" placeholder="date" required />
            </div>

            <div class="form-group">
                <label class="form-label">Days Elapsed</label>
                <input type="text" id="elsp" name="elsp" class="form-control" placeholder="Days Delayed" required />
            </div>

            <div class="form-group">
                <label class="form-label">Fine</label>
                <input type="text" id="fine" name="fine" class="form-control" placeholder="fine" required />
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        }
    </div>

</div>

@section scripts
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery/dist/jquery.js"></script>

    <script>
        getCarid();

        function daysdifference(firstDate, secondDate) {
            var startDay = new Date(firstDate);
            var endDay = new Date(secondDate);

            var millisBetween = startDay.getTime() - endDay.getTime();

            var days = millisBetween / (1000 * 3600 * 24);

            return Math.round(days);
        }


        function getCarid() {
            $("#carno").keyup(function (e) {
                $.ajax({
                    type: 'POST',
                    url: 'ReturnCar/Getid?carno=' + $("#carno").val(),
                    dataType: 'JSON',
                    success: function (data) {
                        console.log(data);
                        $('#custid').val(data[0].custid);
                        $('#date').val(data[0].enddate);

                        var days = daysdifference(new Date(), data[0].enddate);

                        console.log(days);
                        $('#elsp').val(days);

                        if (days > 0) {
                            var fine = days * 100;
                            console.log(fine);
                            $('#fine').val(fine);
                        }
                        else {
                            $('#fine').val("0");
                        }
                    }

                });
            });
        }
    </script>
}